package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"library/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Inventory)
// DB Table: Plural (inventories)
// Resource: Plural (Inventories)
// Path: Plural (/inventories)
// View Template Folder: Plural (/templates/inventories/)

// InventoriesResource is the resource for the Inventory model
type InventoriesResource struct {
	buffalo.Resource
}

// List gets all Inventories. This function is mapped to the path
// GET /inventories
func (v InventoriesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	inventories := &models.Inventories{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Inventories from the DB
	if err := q.Eager().All(inventories); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)
		c.Set("PageTitle", "Inventories List")
		c.Set("inventories", inventories)
		return c.Render(http.StatusOK, r2.HTML("backend/inventories/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r2.JSON(inventories))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r2.XML(inventories))
	}).Respond(c)
}

// Show gets the data for one Inventory. This function is mapped to
// the path GET /inventories/{inventory_id}
func (v InventoriesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Inventory
	inventory := &models.Inventory{}

	// To find the Inventory the parameter inventory_id is used.
	if err := tx.Eager().Find(inventory, c.Param("inventory_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("inventory", inventory)
		c.Set("PageTitle", "Show Inventory")
		return c.Render(http.StatusOK, r2.HTML("backend/inventories/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r2.JSON(inventory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r2.XML(inventory))
	}).Respond(c)
}

// New renders the form for creating a new Inventory.
// This function is mapped to the path GET /inventories/new
func (v InventoriesResource) New(c buffalo.Context) error {
	c.Set("inventory", &models.Inventory{})
	c.Set("PageTitle", "Create Inventory")
	return c.Render(http.StatusOK, r2.HTML("backend/inventories/new.plush.html"))
}

// Create adds a Inventory to the DB. This function is mapped to the
// path POST /inventories
func (v InventoriesResource) Create(c buffalo.Context) error {
	// Allocate an empty Inventory
	inventory := &models.Inventory{}

	// Bind inventory to the html form elements
	if err := c.Bind(inventory); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(inventory)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("inventory", inventory)
			c.Set("PageTitle", "Create Inventory")
			return c.Render(http.StatusUnprocessableEntity, r2.HTML("backend/inventories/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r2.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r2.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "inventory.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/auth/inventories/%v", inventory.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r2.JSON(inventory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r2.XML(inventory))
	}).Respond(c)
}

// Edit renders a edit form for a Inventory. This function is
// mapped to the path GET /inventories/{inventory_id}/edit
func (v InventoriesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Inventory
	inventory := &models.Inventory{}

	if err := tx.Eager().Find(inventory, c.Param("inventory_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("inventory", inventory)
	c.Set("PageTitle", "Edit Inventory")
	return c.Render(http.StatusOK, r2.HTML("backend/inventories/edit.plush.html"))
}

// Update changes a Inventory in the DB. This function is mapped to
// the path PUT /inventories/{inventory_id}
func (v InventoriesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Inventory
	inventory := &models.Inventory{}

	if err := tx.Find(inventory, c.Param("inventory_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Inventory to the html form elements
	if err := c.Bind(inventory); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(inventory)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("inventory", inventory)
			c.Set("PageTitle", "Edit Inventory")
			return c.Render(http.StatusUnprocessableEntity, r2.HTML("backend/inventories/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r2.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r2.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "inventory.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/auth/inventories/%v", inventory.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r2.JSON(inventory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r2.XML(inventory))
	}).Respond(c)
}

// Destroy deletes a Inventory from the DB. This function is mapped
// to the path DELETE /inventories/{inventory_id}
func (v InventoriesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Inventory
	inventory := &models.Inventory{}

	// To find the Inventory the parameter inventory_id is used.
	if err := tx.Find(inventory, c.Param("inventory_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(inventory); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "inventory.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/auth/inventories")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r2.JSON(inventory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r2.XML(inventory))
	}).Respond(c)
}
